DROP PACKAGE ARQ.PKG_EMPLEADO;

CREATE OR REPLACE PACKAGE PKG_EMPLEADO AS

	TYPE C_CURSOR IS REF CURSOR;

	PROCEDURE SP_INSERTAR	(
		P_ID					OUT		EMPLEADO.ID%TYPE,
		P_NOMBRES			IN		EMPLEADO.NOMBRES%TYPE,
		P_APELLIDOS		IN		EMPLEADO.APELLIDOS%TYPE,
		P_DIRECCION		IN		EMPLEADO.DIRECCION%TYPE,
		P_PAIS				IN		EMPLEADO.PAIS%TYPE,
		P_ESTADO			IN		EMPLEADO.ESTADO%TYPE,
		P_SITUACION		IN		EMPLEADO.SITUACION%TYPE
	);
	
	PROCEDURE SP_ACTUALIZAR (
		P_ID					OUT		EMPLEADO.ID%TYPE,
		P_NOMBRES			IN		EMPLEADO.NOMBRES%TYPE,
		P_APELLIDOS		IN		EMPLEADO.APELLIDOS%TYPE,
		P_DIRECCION		IN		EMPLEADO.DIRECCION%TYPE,
		P_PAIS				IN		EMPLEADO.PAIS%TYPE,
		P_ESTADO			IN		EMPLEADO.ESTADO%TYPE,
		P_SITUACION		IN		EMPLEADO.SITUACION%TYPE
	);
	
	PROCEDURE SP_ELIMINAR (
		P_ID					IN		EMPLEADO.ID%TYPE
	);
	
	PROCEDURE SP_LISTA (
		P_C_CURSOR		OUT		C_CURSOR
	);
	
END PKG_EMPLEADO;