CREATE OR REPLACE PACKAGE BODY PKG_EMPLEADO AS

	-- SP_INSERTAR
	PROCEDURE SP_INSERTAR	(
		P_ID					OUT		EMPLEADO.ID%TYPE,
		P_NOMBRES			IN		EMPLEADO.NOMBRES%TYPE,
		P_APELLIDOS		IN		EMPLEADO.APELLIDOS%TYPE,
		P_DIRECCION		IN		EMPLEADO.DIRECCION%TYPE,
		P_PAIS				IN		EMPLEADO.PAIS%TYPE,
		P_ESTADO			IN		EMPLEADO.ESTADO%TYPE,
		P_SITUACION		IN		EMPLEADO.SITUACION%TYPE
	) AS
	BEGIN
		SELECT
					EMPLEADO_SEQ.NEXTVAL
		INTO	P_ID
		FROM DUAL;
		
		INSERT INTO ARQ.EMPLEADO (ID,
															NOMBRES,
															APELLIDOS,
															DIRECCION,
															PAIS,
															ESTADO,
															SITUACION)
		VALUES
			(P_ID, P_NOMBRES, P_APELLIDOS, P_DIRECCION, P_PAIS, P_ESTADO, P_SITUACION);
	END SP_INSERTAR;
	--// SP_INSERTAR
	
	
	-- SP_ACTUALIZAR
	PROCEDURE SP_ACTUALIZAR (
		P_ID					IN		EMPLEADO.ID%TYPE,
		P_NOMBRES			IN		EMPLEADO.NOMBRES%TYPE,
		P_APELLIDOS		IN		EMPLEADO.APELLIDOS%TYPE,
		P_DIRECCION		IN		EMPLEADO.DIRECCION%TYPE,
		P_PAIS				IN		EMPLEADO.PAIS%TYPE,
		P_ESTADO			IN		EMPLEADO.ESTADO%TYPE,
		P_SITUACION		IN		EMPLEADO.SITUACION%TYPE
	) AS
	BEGIN
		UPDATE EMPLEADO
		SET ID				= P_ID,
				NOMBRES		= P_NOMBRES,
				APELLIDOS	= P_APELLIDOS,
				DIRECCION	= P_DIRECCION,
				PAIS			= P_PAIS,
				ESTADO		= P_ESTADO,
				SITUACION	= P_SITUACION
		WHERE 
				ID = P_ID;
	END SP_ACTUALIZAR;
	--// SP_ACTUALIZAR
	
	
	-- SP_ELIMINAR
	PROCEDURE SP_ELIMINAR (
		P_ID					IN		EMPLEADO.ID%TYPE
	) AS
	BEGIN
		UPDATE	ARQ.EMPLEADO
		SET	ESTADO = '0'
		WHERE
				ID = P_ID;
	END SP_ELIMINAR;
	--// SP_ELIMINAR
	
	
	-- SP_LISTA
	PROCEDURE SP_LISTA (
		P_C_CURSOR		OUT		C_CURSOR
	) AS
	BEGIN
		OPEN
				P_C_CURSOR
		FOR
				SELECT 
						ID,
						NOMBRES,
						APELLIDOS,
						DIRECCION,
						PAIS,
						ESTADO,
						SITUACION
				FROM ARQ.EMPLEADO
				ORDER BY NOMBRES;
	END SP_LISTA;
	--// SP_LISTA
	
	
END PKG_EMPLEADO;